target.c: prerequest1 prerequest2 prerequest3
	@echo 'target: prerequest1 prerequest2 prerequest3'
	@echo '$$@: '$@
	@echo '$$*: '$*
	@echo '$$<: '$<
	@echo '$$^: '$^
	@echo 'ref: http://www.gnu.org/software/make/manual/make.html'

prerequest1:
prerequest2:
prerequest3:
